// Writes worker/content.gen.js: the story levels the Worker needs to verify results and the story beat ids it
// accepts in a seen list (it cannot glob the content/ folder at runtime). Run automatically by `npm run build` and the worker tests.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadPacks, loadStory, ROOT, LEVELS_DIR } from './lib/content.js';
import { storyIds } from '../client/game/story.js';

const packs = loadPacks();
const levels = {};
const story = [];
for (const p of packs) {
  for (const { level, id } of p.levels) {
    if (!level) continue;
    levels[id] = level;
    story.push(id);
  }
}
const share = JSON.parse(readFileSync(join(LEVELS_DIR, 'share-index.json'), 'utf8')).levels;
const out = `// GENERATED by scripts/build-content.js - do not edit. Story levels for server-side result verification.
export const STORY = ${JSON.stringify(story)};
export const SHARE = ${JSON.stringify(share)};
export const LEVELS = ${JSON.stringify(levels)};
// story beat + keepsake ids (content/story): the only ids a player's seen list may hold
export const STORY_SEEN_IDS = ${JSON.stringify(storyIds(loadStory()))};
`;
writeFileSync(join(ROOT, 'worker', 'content.gen.js'), out);
console.log(`worker/content.gen.js: ${story.length} levels`);
