// Writes worker/content.gen.js: the story levels the Worker needs to verify results (it cannot glob the content/
// folder at runtime). Run automatically by `npm run build` and the worker tests.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadPacks, ROOT } from './lib/content.js';

const packs = loadPacks();
const levels = {};
const story = [];
for (const p of packs) {
  for (const { level, id } of p.levels) {
    if (!level) continue;
    levels[id] = level;
    story.push(id);
  }
}
const out = `// GENERATED by scripts/build-content.js - do not edit. Story levels for server-side result verification.
export const STORY = ${JSON.stringify(story)};
export const LEVELS = ${JSON.stringify(levels)};
`;
writeFileSync(join(ROOT, 'worker', 'content.gen.js'), out);
console.log(`worker/content.gen.js: ${story.length} levels`);
